### ISSUE TITLE
RuntimeError: CUDA driver error: file not found

### ISSUE THREAD

**Issue by GolovanPriherel** [kijai/ComfyUI-WanVideoWrapper#1093]
Recently installed the latest portable version of ComfyUI for video generation using Wan 2.2. I downloaded KJ workflows, installed all the nodes and on the WanVideo Sampler node I have this repeating error.

I tried different versions of torch, installed desktop with python 3.12, installed triton, added the scripts folder to the PATH and none of this helped.

I also tried the default workflow for Wan 2.2 and it works, but when I use KJ workflow, I always get this error.

# ComfyUI Error Report
## Error Details
- **Node ID:** 308
- **Node Type:** WanVideoSampler
- **Exception Type:** torch._inductor.exc.InductorError
- **Exception Message:** RuntimeError: CUDA driver error: file not found

Set TORCHDYNAMO_VERBOSE=1 for the internal stack trace (please do this especially if you're reporting a bug to PyTorch). For even more developer context, set TORCH_LOGS="+dynamo"

## Stack Trace
```
  File "E:\Igri\comfyui\ComfyUI\execution.py", line 496, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\Igri\comfyui\ComfyUI\execution.py", line 315, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\Igri\comfyui\ComfyUI\execution.py", line 289, in _async_map_node_over_list
    await process_inputs(input_dict, i)

  File "E:\Igri\comfyui\ComfyUI\execution.py", line 277, in process_inputs
    result = f(**inputs)

  File "E:\Igri\comfyui\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\nodes.py", line 3591, in process
    raise e

  File "E:\Igri\comfyui\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\nodes.py", line 3485, in process
    noise_pred, self.cache_state = predict_with_cfg(
                                   ~~~~~~~~~~~~~~~~^
        latent_model_input,
        ^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
        timestep, idx, image_cond, clip_fea, control_latents, vace_data, unianim_data, audio_proj, control_camera_latents, add_cond,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        cache_state=self.cache_state, fantasy_portrait_input=fantasy_portrait_input)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\Igri\comfyui\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\nodes.py", line 2610, in predict_with_cfg
    raise e

  File "E:\Igri\comfyui\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\nodes.py", line 2511, in predict_with_cfg
    noise_pred_cond, cache_state_cond = transformer(
                                        ~~~~~~~~~~~^
        [z_pos], context=positive_embeds, y=[image_cond_input] if image_cond_input is not None else None,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
        **base_params
        ^^^^^^^^^^^^^
    )
    ^

  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1773, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^

  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1784, in _call_impl
    return forward_call(*args, **kwargs)

  File "E:\Igri\comfyui\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\wanvideo\modules\model.py", line 2074, in forward
    x, x_ip = block(x, x_ip=x_ip, **kwargs)
              ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_dynamo\eval_frame.py", line 375, in __call__
    return super().__call__(*args, **kwargs)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^

  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1773, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^

  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1784, in _call_impl
    return forward_call(*args, **kwargs)

  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_dynamo\eval_frame.py", line 749, in compile_wrapper
    raise e.remove_dynamo_frames() from None  # see TORCHDYNAMO_VERBOSE=1
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_inductor\compile_fx.py", line 923, in _compile_fx_inner
    raise InductorError(e, currentframe()).with_traceback(
        e.__traceback__
    ) from None

  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_inductor\compile_fx.py", line 907, in _compile_fx_inner
    mb_compiled_graph = fx_codegen_and_compile(
        gm, example_inputs, inputs_to_check, **graph_kwargs
    )

  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_inductor\compile_fx.py", line 1578, in fx_codegen_and_compile
    return scheme.codegen_and_compile(gm, example_inputs, inputs_to_check, graph_kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_inductor\compile_fx.py", line 1456, in codegen_and_compile
    compiled_module = graph.compile_to_module()

  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_inductor\graph.py", line 2293, in compile_to_module
    return self._compile_to_module()
           ~~~~~~~~~~~~~~~~~~~~~~~^^

  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_inductor\graph.py", line 2303, in _compile_to_module
    mod = self._compile_to_module_lines(wrapper_code)

  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_inductor\graph.py", line 2371, in _compile_to_module_lines
    mod = PyCodeCache.load_by_key_path(
        key,
    ...<2 lines>...
        attrs={**self.constants, **self.torchbind_constants},
    )

  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_inductor\codecache.py", line 3296, in load_by_key_path
    mod = _reload_python_module(key, path, set_sys_modules=in_toplevel)

  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_inductor\runtime\compile_tasks.py", line 31, in _reload_python_module
    exec(code, mod.__dict__, mod.__dict__)
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Temp\torchinductor_user123\k4\ck4aty3soay34puqlm5phdtjqapxreymgqhgpo3top46llmgcie5.py", line 55, in <module>

  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_inductor\async_compile.py", line 404, in triton
    kernel.precompile(
    ~~~~~~~~~~~~~~~~~^
        warm_cache_only=False,
        ^^^^^^^^^^^^^^^^^^^^^^
        static_triton_bundle_key=CompiledTritonKernels.key(source_code),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^

  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_inductor\runtime\triton_heuristics.py", line 411, in precompile
    self._make_launchers()
    ~~~~~~~~~~~~~~~~~~~~^^

  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_inductor\runtime\triton_heuristics.py", line 568, in _make_launchers
    launchers.append(result.make_launcher())
                     ~~~~~~~~~~~~~~~~~~~~^^

  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_inductor\runtime\triton_heuristics.py", line 1415, in make_launcher
    self.kernel.load_kernel(device)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^

  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_inductor\runtime\static_cuda_launcher.py", line 113, in load_kernel
    (self.function, self.n_regs, self.n_spills) = _StaticCudaLauncher._load_kernel(
                                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self.cubin_path, self.name, self.shared, device
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^

```
## System Information
- **ComfyUI Version:** 0.3.51
- **Arguments:** ComfyUI\main.py --windows-standalone-build --disable-auto-launch --disable-smart-memory
- **OS:** nt
- **Python Version:** 3.13.6 (tags/v3.13.6:4e66535, Aug  6 2025, 14:36:00) [MSC v.1944 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.8.0+cu129
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 25769148416
  - **VRAM Free:** 24291612160
  - **Torch VRAM Total:** 167772160
  - **Torch VRAM Free:** 100963840

## Logs
```
2025-08-23T03:27:22.426829 - [START] Security scan2025-08-23T03:27:22.426852 - 
2025-08-23T03:27:22.989467 - [DONE] Security scan2025-08-23T03:27:22.989482 - 
2025-08-23T03:27:23.072754 - ## ComfyUI-Manager: installing dependencies done.2025-08-23T03:27:23.072859 - 
2025-08-23T03:27:23.072980 - ** ComfyUI startup time:2025-08-23T03:27:23.073036 -  2025-08-23T03:27:23.073111 - 2025-08-23 03:27:23.0722025-08-23T03:27:23.073324 - 
2025-08-23T03:27:23.073387 - ** Platform:2025-08-23T03:27:23.073438 -  2025-08-23T03:27:23.073481 - Windows2025-08-23T03:27:23.073522 - 
2025-08-23T03:27:23.073562 - ** Python version:2025-08-23T03:27:23.073603 -  2025-08-23T03:27:23.073642 - 3.13.6 (tags/v3.13.6:4e66535, Aug  6 2025, 14:36:00) [MSC v.1944 64 bit (AMD64)]2025-08-23T03:27:23.073687 - 
2025-08-23T03:27:23.073727 - ** Python executable:2025-08-23T03:27:23.073769 -  2025-08-23T03:27:23.073815 - E:\Igri\comfyui\python_embeded\python.exe2025-08-23T03:27:23.073856 - 
2025-08-23T03:27:23.073895 - ** ComfyUI Path:2025-08-23T03:27:23.073933 -  2025-08-23T03:27:23.073970 - E:\Igri\comfyui\ComfyUI2025-08-23T03:27:23.074008 - 
2025-08-23T03:27:23.074046 - ** ComfyUI Base Folder Path:2025-08-23T03:27:23.074084 -  2025-08-23T03:27:23.074120 - E:\Igri\comfyui\ComfyUI2025-08-23T03:27:23.074157 - 
2025-08-23T03:27:23.074194 - ** User directory:2025-08-23T03:27:23.074231 -  2025-08-23T03:27:23.074280 - E:\Igri\comfyui\ComfyUI\user2025-08-23T03:27:23.074322 - 
2025-08-23T03:27:23.074361 - ** ComfyUI-Manager config path:2025-08-23T03:27:23.074399 -  2025-08-23T03:27:23.074593 - E:\Igri\comfyui\ComfyUI\user\default\ComfyUI-Manager\config.ini2025-08-23T03:27:23.074633 - 
2025-08-23T03:27:23.074669 - ** Log path:2025-08-23T03:27:23.074699 -  2025-08-23T03:27:23.074727 - E:\Igri\comfyui\ComfyUI\user\comfyui.log2025-08-23T03:27:23.074756 - 
2025-08-23T03:27:23.831395 - 
Prestartup times for custom nodes:
2025-08-23T03:27:23.831541 -    1.8 seconds: E:\Igri\comfyui\ComfyUI\custom_nodes\comfyui-manager
2025-08-23T03:27:23.831732 - 
2025-08-23T03:27:25.082023 - Checkpoint files will always be loaded safely.
2025-08-23T03:27:25.175154 - Total VRAM 24575 MB, total RAM 65480 MB
2025-08-23T03:27:25.175334 - pytorch version: 2.8.0+cu129
2025-08-23T03:27:26.332600 - xformers version: 0.0.32.post2
2025-08-23T03:27:26.332785 - Set vram state to: NORMAL_VRAM
2025-08-23T03:27:26.332892 - Disabling smart memory management
2025-08-23T03:27:26.333016 - Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
2025-08-23T03:27:26.519805 - Using xformers attention
2025-08-23T03:27:27.790245 - Python version: 3.13.6 (tags/v3.13.6:4e66535, Aug  6 2025, 14:36:00) [MSC v.1944 64 bit (AMD64)]
2025-08-23T03:27:27.790397 - ComfyUI version: 0.3.51
2025-08-23T03:27:27.806774 - ComfyUI frontend version: 1.25.9
2025-08-23T03:27:27.807642 - [Prompt Server] web root: E:\Igri\comfyui\python_embeded\Lib\site-packages\comfyui_frontend_package\static
2025-08-23T03:27:29.003553 - ### Loading: ComfyUI-Manager (V3.36)
2025-08-23T03:27:29.004285 - [ComfyUI-Manager] network_mode: public
2025-08-23T03:27:29.067944 - ### ComfyUI Revision: 189 [7139d6d9] *DETACHED | Released on '2025-08-20'
2025-08-23T03:27:29.251817 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
2025-08-23T03:27:29.262229 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
2025-08-23T03:27:29.343967 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
2025-08-23T03:27:29.424304 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
2025-08-23T03:27:29.469755 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
2025-08-23T03:27:31.344649 - FantasyPortrait nodes not available due to error in importing them: No module named 'onnxruntime'2025-08-23T03:27:31.344761 - 
2025-08-23T03:27:31.355301 - 
Import times for custom nodes:
2025-08-23T03:27:31.355441 -    0.0 seconds: E:\Igri\comfyui\ComfyUI\custom_nodes\websocket_image_save.py
2025-08-23T03:27:31.355674 -    0.0 seconds: E:\Igri\comfyui\ComfyUI\custom_nodes\cg-use-everywhere
2025-08-23T03:27:31.355872 -    0.0 seconds: E:\Igri\comfyui\ComfyUI\custom_nodes\comfyui-mxtoolkit
2025-08-23T03:27:31.356126 -    0.0 seconds: E:\Igri\comfyui\ComfyUI\custom_nodes\ComfyUI-DepthAnythingV2
2025-08-23T03:27:31.356360 -    0.0 seconds: E:\Igri\comfyui\ComfyUI\custom_nodes\comfyui-custom-scripts
2025-08-23T03:27:31.356582 -    0.0 seconds: E:\Igri\comfyui\ComfyUI\custom_nodes\ComfyUI-Chibi-Nodes
2025-08-23T03:27:31.356790 -    0.0 seconds: E:\Igri\comfyui\ComfyUI\custom_nodes\comfyui_essentials
2025-08-23T03:27:31.357001 -    0.0 seconds: E:\Igri\comfyui\ComfyUI\custom_nodes\comfyui-various
2025-08-23T03:27:31.357208 -    0.0 seconds: E:\Igri\comfyui\ComfyUI\custom_nodes\comfyui-dream-video-batches
2025-08-23T03:27:31.357449 -    0.0 seconds: E:\Igri\comfyui\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
2025-08-23T03:27:31.357714 -    0.0 seconds: E:\Igri\comfyui\ComfyUI\custom_nodes\comfyui-kjnodes
2025-08-23T03:27:31.357997 -    0.1 seconds: E:\Igri\comfyui\ComfyUI\custom_nodes\comfyui-manager
2025-08-23T03:27:31.358176 -    0.4 seconds: E:\Igri\comfyui\ComfyUI\custom_nodes\comfyui-florence2
2025-08-23T03:27:31.358386 -    2.2 seconds: E:\Igri\comfyui\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper
2025-08-23T03:27:31.358595 - 
2025-08-23T03:27:31.560281 - Context impl SQLiteImpl.
2025-08-23T03:27:31.560463 - Will assume non-transactional DDL.
2025-08-23T03:27:31.561774 - No target revision found.
2025-08-23T03:27:31.574879 - Starting server

2025-08-23T03:27:31.575243 - To see the GUI go to: http://127.0.0.1:8188
2025-08-23T03:27:34.033545 - FETCH ComfyRegistry Data: 5/952025-08-23T03:27:34.033665 - 
2025-08-23T03:27:38.901119 - FETCH ComfyRegistry Data: 10/952025-08-23T03:27:38.901236 - 
2025-08-23T03:27:43.171857 - FETCH ComfyRegistry Data: 15/952025-08-23T03:27:43.171981 - 
2025-08-23T03:27:47.996955 - FETCH ComfyRegistry Data: 20/952025-08-23T03:27:47.997081 - 
2025-08-23T03:27:52.214960 - FETCH ComfyRegistry Data: 25/952025-08-23T03:27:52.215083 - 
2025-08-23T03:27:56.666759 - FETCH ComfyRegistry Data: 30/952025-08-23T03:27:56.666857 - 
2025-08-23T03:28:01.144399 - FETCH ComfyRegistry Data: 35/952025-08-23T03:28:01.144486 - 
2025-08-23T03:28:05.582641 - FETCH ComfyRegistry Data: 40/952025-08-23T03:28:05.582760 - 
2025-08-23T03:28:05.631827 - [ComfyUI-Manager] The ComfyRegistry cache update is still in progress, so an outdated cache is being used.2025-08-23T03:28:05.631951 - 
2025-08-23T03:28:05.673706 - FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json2025-08-23T03:28:05.673806 - 2025-08-23T03:28:06.018912 -  [DONE]2025-08-23T03:28:06.019012 - 
2025-08-23T03:28:06.089916 - FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json2025-08-23T03:28:06.090015 - 2025-08-23T03:28:06.338189 -  [DONE]2025-08-23T03:28:06.338296 - 
2025-08-23T03:28:06.354930 - FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extras.json2025-08-23T03:28:06.355000 - 2025-08-23T03:28:06.523870 -  [DONE]2025-08-23T03:28:06.523956 - 
2025-08-23T03:28:06.594101 - FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json2025-08-23T03:28:06.594238 - 2025-08-23T03:28:06.901632 -  [DONE]2025-08-23T03:28:06.901727 - 
2025-08-23T03:28:07.915208 - [ComfyUI-Manager] The ComfyRegistry cache update is still in progress, so an outdated cache is being used.2025-08-23T03:28:07.915311 - 
2025-08-23T03:28:07.959625 - FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json2025-08-23T03:28:07.959722 - 2025-08-23T03:28:08.270062 -  [DONE]2025-08-23T03:28:08.270156 - 
2025-08-23T03:28:08.342062 - FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json2025-08-23T03:28:08.342208 - 2025-08-23T03:28:08.590130 -  [DONE]2025-08-23T03:28:08.590239 - 
2025-08-23T03:28:08.606948 - FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extras.json2025-08-23T03:28:08.607003 - 2025-08-23T03:28:08.775339 -  [DONE]2025-08-23T03:28:08.775439 - 
2025-08-23T03:28:08.838987 - FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json2025-08-23T03:28:08.839146 - 2025-08-23T03:28:09.148971 -  [DONE]2025-08-23T03:28:09.149077 - 
2025-08-23T03:28:10.186465 - FETCH ComfyRegistry Data: 45/952025-08-23T03:28:10.186576 - 
2025-08-23T03:28:14.989646 - FETCH ComfyRegistry Data: 50/952025-08-23T03:28:14.989784 - 
2025-08-23T03:28:19.275835 - FETCH ComfyRegistry Data: 55/952025-08-23T03:28:19.275924 - 
2025-08-23T03:28:24.680437 - FETCH ComfyRegistry Data: 60/952025-08-23T03:28:24.680543 - 
2025-08-23T03:28:30.108155 - FETCH ComfyRegistry Data: 65/952025-08-23T03:28:30.108253 - 
2025-08-23T03:28:34.686602 - FETCH ComfyRegistry Data: 70/952025-08-23T03:28:34.686709 - 
2025-08-23T03:28:49.640620 - FETCH ComfyRegistry Data: 75/952025-08-23T03:28:49.640715 - 
2025-08-23T03:28:55.974244 - FETCH ComfyRegistry Data: 80/952025-08-23T03:28:55.974331 - 
2025-08-23T03:29:01.476489 - FETCH ComfyRegistry Data: 85/952025-08-23T03:29:01.476600 - 
2025-08-23T03:29:05.812445 - FETCH ComfyRegistry Data: 90/952025-08-23T03:29:05.812565 - 
2025-08-23T03:29:07.272955 - got prompt
2025-08-23T03:29:07.282471 - WARNING: PlaySound.IS_CHANGED() missing 1 required positional argument: 'self'
2025-08-23T03:29:08.596305 - Loading prompt embeds from cache: E:\Igri\comfyui\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\text_embed_cache\247e95d8ce4e7e3458284b905585c263108ae7682b387eaff193b4397c7cd86e.pt
2025-08-23T03:29:08.607490 - Loading prompt embeds from cache: E:\Igri\comfyui\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\text_embed_cache\4ec086997aa34571ae4b4eb8d31555d0cdd9a81fc3f28b6c193228de4cec6e45.pt
2025-08-23T03:29:11.089961 - FETCH ComfyRegistry Data: 95/952025-08-23T03:29:11.090091 - 
2025-08-23T03:29:11.590991 - FETCH ComfyRegistry Data [DONE]2025-08-23T03:29:11.591129 - 
2025-08-23T03:29:11.719694 - [ComfyUI-Manager] default cache updated: https://api.comfy.org/nodes
2025-08-23T03:29:11.742981 - FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json2025-08-23T03:29:11.743047 - 2025-08-23T03:29:12.060896 -  [DONE]2025-08-23T03:29:12.060999 - 
2025-08-23T03:29:12.116002 - [ComfyUI-Manager] All startup tasks have been completed.
2025-08-23T03:29:14.893287 - CUDA Compute Capability: 8.6
2025-08-23T03:29:14.893545 - Torch.compile with fp8_e4m3fn weights on CUDA compute capability < 8.9 is not supported. Please use fp8_e5m2, GGUF or higher precision instead.
2025-08-23T03:29:14.894278 - Detected model in_channels: 36
2025-08-23T03:29:14.894577 - Model cross attention type: t2v, num_heads: 40, num_layers: 40
2025-08-23T03:29:14.894883 - Model variant detected: 14B
2025-08-23T03:29:14.984217 - model_type FLOW
2025-08-23T03:29:15.090363 - Using accelerate to load and assign model weights to device...
2025-08-23T03:29:15.195245 - 
Loading transformer parameters to cpu:  74%|████████████████████████████▏         | 814/1095 [00:00<00:00, 8139.56it/s]2025-08-23T03:29:15.206437 - 
Loading transformer parameters to cpu: 100%|█████████████████████████████████████| 1095/1095 [00:00<00:00, 9847.09it/s]2025-08-23T03:29:15.206546 - 
2025-08-23T03:29:15.212298 - Moving diffusion model from cuda:0 to cpu
2025-08-23T03:29:15.521903 - Loading LoRA: Wan2.2-Lightning_T2V-A14B-4steps-lora_HIGH_fp16 with strength: 1.0
2025-08-23T03:29:15.572947 - Using 400 LoRA weight patches for WanVideo model
2025-08-23T03:29:15.635744 - sigmas: tensor([1.0000, 0.9824, 0.9600, 0.9302, 0.8889, 0.8276, 0.7272, 0.5333, 0.0000])
2025-08-23T03:29:15.636084 - Sampling until step 4, timestep: 930
2025-08-23T03:29:15.636870 - timesteps: tensor([999, 982, 959, 930], device='cuda:0')
2025-08-23T03:29:15.637152 - image_cond shape: torch.Size([20, 21, 68, 104])
2025-08-23T03:29:15.979011 - Swapping 10 transformer blocks
2025-08-23T03:29:19.405408 - 
Initializing block swap: 100%|█████████████████████████████████████████████████████████| 40/40 [00:03<00:00,  9.43it/s]2025-08-23T03:29:19.405669 - 
Initializing block swap: 100%|█████████████████████████████████████████████████████████| 40/40 [00:03<00:00, 11.68it/s]2025-08-23T03:29:19.405730 - 
2025-08-23T03:29:19.659056 - ----------------------
2025-08-23T03:29:19.659240 - Block swap memory summary:
2025-08-23T03:29:19.659955 - Transformer blocks on cpu: 3352.31MB
2025-08-23T03:29:19.660153 - Transformer blocks on cuda:0: 10056.94MB
2025-08-23T03:29:19.660376 - Total memory used by transformer blocks: 13409.26MB
2025-08-23T03:29:19.660590 - Non-blocking memory transfer: True
2025-08-23T03:29:19.660789 - ----------------------
2025-08-23T03:29:19.661781 - Input sequence length: 37128
2025-08-23T03:29:19.661910 - Sampling 81 frames at 832x544 with 8 steps
2025-08-23T03:29:19.930392 - 
  0%|                                                                                            | 0/4 [00:00<?, ?it/s]2025-08-23T03:29:21.130430 - Error during model prediction: RuntimeError: CUDA driver error: file not found

Set TORCHDYNAMO_VERBOSE=1 for the internal stack trace (please do this especially if you're reporting a bug to PyTorch). For even more developer context, set TORCH_LOGS="+dynamo"

2025-08-23T03:29:24.016931 - 
  0%|                                                                                            | 0/4 [00:04<?, ?it/s]2025-08-23T03:29:24.017049 - 
2025-08-23T03:29:24.017346 - Error during sampling: RuntimeError: CUDA driver error: file not found

Set TORCHDYNAMO_VERBOSE=1 for the internal stack trace (please do this especially if you're reporting a bug to PyTorch). For even more developer context, set TORCH_LOGS="+dynamo"

2025-08-23T03:29:24.430470 - !!! Exception during processing !!! RuntimeError: CUDA driver error: file not found

Set TORCHDYNAMO_VERBOSE=1 for the internal stack trace (please do this especially if you're reporting a bug to PyTorch). For even more developer context, set TORCH_LOGS="+dynamo"

2025-08-23T03:29:24.448606 - Traceback (most recent call last):
  File "E:\Igri\comfyui\ComfyUI\execution.py", line 496, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Igri\comfyui\ComfyUI\execution.py", line 315, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Igri\comfyui\ComfyUI\execution.py", line 289, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "E:\Igri\comfyui\ComfyUI\execution.py", line 277, in process_inputs
    result = f(**inputs)
  File "E:\Igri\comfyui\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\nodes.py", line 3591, in process
    raise e
  File "E:\Igri\comfyui\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\nodes.py", line 3485, in process
    noise_pred, self.cache_state = predict_with_cfg(
                                   ~~~~~~~~~~~~~~~~^
        latent_model_input,
        ^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
        timestep, idx, image_cond, clip_fea, control_latents, vace_data, unianim_data, audio_proj, control_camera_latents, add_cond,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        cache_state=self.cache_state, fantasy_portrait_input=fantasy_portrait_input)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Igri\comfyui\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\nodes.py", line 2610, in predict_with_cfg
    raise e
  File "E:\Igri\comfyui\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\nodes.py", line 2511, in predict_with_cfg
    noise_pred_cond, cache_state_cond = transformer(
                                        ~~~~~~~~~~~^
        [z_pos], context=positive_embeds, y=[image_cond_input] if image_cond_input is not None else None,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
        **base_params
        ^^^^^^^^^^^^^
    )
    ^
  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1773, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1784, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Igri\comfyui\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\wanvideo\modules\model.py", line 2074, in forward
    x, x_ip = block(x, x_ip=x_ip, **kwargs)
              ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_dynamo\eval_frame.py", line 375, in __call__
    return super().__call__(*args, **kwargs)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1773, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1784, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_dynamo\eval_frame.py", line 749, in compile_wrapper
    raise e.remove_dynamo_frames() from None  # see TORCHDYNAMO_VERBOSE=1
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_inductor\compile_fx.py", line 923, in _compile_fx_inner
    raise InductorError(e, currentframe()).with_traceback(
        e.__traceback__
    ) from None
  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_inductor\compile_fx.py", line 907, in _compile_fx_inner
    mb_compiled_graph = fx_codegen_and_compile(
        gm, example_inputs, inputs_to_check, **graph_kwargs
    )
  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_inductor\compile_fx.py", line 1578, in fx_codegen_and_compile
    return scheme.codegen_and_compile(gm, example_inputs, inputs_to_check, graph_kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_inductor\compile_fx.py", line 1456, in codegen_and_compile
    compiled_module = graph.compile_to_module()
  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_inductor\graph.py", line 2293, in compile_to_module
    return self._compile_to_module()
           ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_inductor\graph.py", line 2303, in _compile_to_module
    mod = self._compile_to_module_lines(wrapper_code)
  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_inductor\graph.py", line 2371, in _compile_to_module_lines
    mod = PyCodeCache.load_by_key_path(
        key,
    ...<2 lines>...
        attrs={**self.constants, **self.torchbind_constants},
    )
  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_inductor\codecache.py", line 3296, in load_by_key_path
    mod = _reload_python_module(key, path, set_sys_modules=in_toplevel)
  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_inductor\runtime\compile_tasks.py", line 31, in _reload_python_module
    exec(code, mod.__dict__, mod.__dict__)
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Temp\torchinductor_user123\wt\cwtp74kzyyziopjwdid5dskythkodhkj5mix3lq3sgosxgrshko5.py", line 55, in <module>
  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_inductor\async_compile.py", line 404, in triton
    kernel.precompile(
    ~~~~~~~~~~~~~~~~~^
        warm_cache_only=False,
        ^^^^^^^^^^^^^^^^^^^^^^
        static_triton_bundle_key=CompiledTritonKernels.key(source_code),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_inductor\runtime\triton_heuristics.py", line 411, in precompile
    self._make_launchers()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_inductor\runtime\triton_heuristics.py", line 568, in _make_launchers
    launchers.append(result.make_launcher())
                     ~~~~~~~~~~~~~~~~~~~~^^
  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_inductor\runtime\triton_heuristics.py", line 1415, in make_launcher
    self.kernel.load_kernel(device)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_inductor\runtime\static_cuda_launcher.py", line 113, in load_kernel
    (self.function, self.n_regs, self.n_spills) = _StaticCudaLauncher._load_kernel(
                                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self.cubin_path, self.name, self.shared, device
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
torch._inductor.exc.InductorError: RuntimeError: CUDA driver error: file not found

Set TORCHDYNAMO_VERBOSE=1 for the internal stack trace (please do this especially if you're reporting a bug to PyTorch). For even more developer context, set TORCH_LOGS="+dynamo"


2025-08-23T03:29:24.466736 - Prompt executed in 17.19 seconds
2025-08-23T03:43:12.480996 - got prompt
2025-08-23T03:43:12.491179 - WARNING: PlaySound.IS_CHANGED() missing 1 required positional argument: 'self'
2025-08-23T03:43:12.508043 - Loading LoRA: Wan2.2-Lightning_I2V-A14B-4steps-lora_HIGH_fp16 with strength: 1.0
2025-08-23T03:43:12.564381 - Using 400 LoRA weight patches for WanVideo model
2025-08-23T03:43:12.628766 - sigmas: tensor([1.0000, 0.9824, 0.9600, 0.9302, 0.8889, 0.8276, 0.7272, 0.5333, 0.0000])
2025-08-23T03:43:12.628986 - Sampling until step 4, timestep: 930
2025-08-23T03:43:12.629343 - timesteps: tensor([999, 982, 959, 930], device='cuda:0')
2025-08-23T03:43:12.629575 - image_cond shape: torch.Size([20, 21, 68, 104])
2025-08-23T03:43:13.006951 - Swapping 10 transformer blocks
2025-08-23T03:43:14.714473 - 
Initializing block swap:  95%|██████████████████████████████████████████████████████▏  | 38/40 [00:01<00:00, 18.48it/s]2025-08-23T03:43:14.890546 - 
Initializing block swap: 100%|█████████████████████████████████████████████████████████| 40/40 [00:01<00:00, 21.25it/s]2025-08-23T03:43:14.890767 - 
2025-08-23T03:43:15.219791 - ----------------------
2025-08-23T03:43:15.219962 - Block swap memory summary:
2025-08-23T03:43:15.220674 - Transformer blocks on cpu: 3352.31MB
2025-08-23T03:43:15.220825 - Transformer blocks on cuda:0: 10056.94MB
2025-08-23T03:43:15.221018 - Total memory used by transformer blocks: 13409.26MB
2025-08-23T03:43:15.221216 - Non-blocking memory transfer: True
2025-08-23T03:43:15.221403 - ----------------------
2025-08-23T03:43:15.221867 - Input sequence length: 37128
2025-08-23T03:43:15.221972 - Sampling 81 frames at 832x544 with 8 steps
2025-08-23T03:43:15.508841 - 
  0%|                                                                                            | 0/4 [00:00<?, ?it/s]2025-08-23T03:43:15.726898 - Error during model prediction: RuntimeError: CUDA driver error: file not found

Set TORCHDYNAMO_VERBOSE=1 for the internal stack trace (please do this especially if you're reporting a bug to PyTorch). For even more developer context, set TORCH_LOGS="+dynamo"

2025-08-23T03:43:18.602990 - 
  0%|                                                                                            | 0/4 [00:03<?, ?it/s]2025-08-23T03:43:18.603088 - 
2025-08-23T03:43:18.603363 - Error during sampling: RuntimeError: CUDA driver error: file not found

Set TORCHDYNAMO_VERBOSE=1 for the internal stack trace (please do this especially if you're reporting a bug to PyTorch). For even more developer context, set TORCH_LOGS="+dynamo"

2025-08-23T03:43:18.963162 - !!! Exception during processing !!! RuntimeError: CUDA driver error: file not found

Set TORCHDYNAMO_VERBOSE=1 for the internal stack trace (please do this especially if you're reporting a bug to PyTorch). For even more developer context, set TORCH_LOGS="+dynamo"

2025-08-23T03:43:18.979077 - Traceback (most recent call last):
  File "E:\Igri\comfyui\ComfyUI\execution.py", line 496, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Igri\comfyui\ComfyUI\execution.py", line 315, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Igri\comfyui\ComfyUI\execution.py", line 289, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "E:\Igri\comfyui\ComfyUI\execution.py", line 277, in process_inputs
    result = f(**inputs)
  File "E:\Igri\comfyui\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\nodes.py", line 3591, in process
    raise e
  File "E:\Igri\comfyui\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\nodes.py", line 3485, in process
    noise_pred, self.cache_state = predict_with_cfg(
                                   ~~~~~~~~~~~~~~~~^
        latent_model_input,
        ^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
        timestep, idx, image_cond, clip_fea, control_latents, vace_data, unianim_data, audio_proj, control_camera_latents, add_cond,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        cache_state=self.cache_state, fantasy_portrait_input=fantasy_portrait_input)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Igri\comfyui\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\nodes.py", line 2610, in predict_with_cfg
    raise e
  File "E:\Igri\comfyui\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\nodes.py", line 2511, in predict_with_cfg
    noise_pred_cond, cache_state_cond = transformer(
                                        ~~~~~~~~~~~^
        [z_pos], context=positive_embeds, y=[image_cond_input] if image_cond_input is not None else None,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
        **base_params
        ^^^^^^^^^^^^^
    )
    ^
  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1773, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1784, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Igri\comfyui\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\wanvideo\modules\model.py", line 2074, in forward
    x, x_ip = block(x, x_ip=x_ip, **kwargs)
              ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_dynamo\eval_frame.py", line 375, in __call__
    return super().__call__(*args, **kwargs)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1773, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1784, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_dynamo\eval_frame.py", line 749, in compile_wrapper
    raise e.remove_dynamo_frames() from None  # see TORCHDYNAMO_VERBOSE=1
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_inductor\compile_fx.py", line 923, in _compile_fx_inner
    raise InductorError(e, currentframe()).with_traceback(
        e.__traceback__
    ) from None
  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_inductor\compile_fx.py", line 907, in _compile_fx_inner
    mb_compiled_graph = fx_codegen_and_compile(
        gm, example_inputs, inputs_to_check, **graph_kwargs
    )
  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_inductor\compile_fx.py", line 1578, in fx_codegen_and_compile
    return scheme.codegen_and_compile(gm, example_inputs, inputs_to_check, graph_kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_inductor\compile_fx.py", line 1456, in codegen_and_compile
    compiled_module = graph.compile_to_module()
  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_inductor\graph.py", line 2293, in compile_to_module
    return self._compile_to_module()
           ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_inductor\graph.py", line 2303, in _compile_to_module
    mod = self._compile_to_module_lines(wrapper_code)
  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_inductor\graph.py", line 2371, in _compile_to_module_lines
    mod = PyCodeCache.load_by_key_path(
        key,
    ...<2 lines>...
        attrs={**self.constants, **self.torchbind_constants},
    )
  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_inductor\codecache.py", line 3296, in load_by_key_path
    mod = _reload_python_module(key, path, set_sys_modules=in_toplevel)
  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_inductor\runtime\compile_tasks.py", line 31, in _reload_python_module
    exec(code, mod.__dict__, mod.__dict__)
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Temp\torchinductor_user123\ru\cruyn2u2zxoabkzgdmawutne47fxzgfwqvqjtf3slwpdjhamhl5m.py", line 55, in <module>
  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_inductor\async_compile.py", line 404, in triton
    kernel.precompile(
    ~~~~~~~~~~~~~~~~~^
        warm_cache_only=False,
        ^^^^^^^^^^^^^^^^^^^^^^
        static_triton_bundle_key=CompiledTritonKernels.key(source_code),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_inductor\runtime\triton_heuristics.py", line 411, in precompile
    self._make_launchers()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_inductor\runtime\triton_heuristics.py", line 568, in _make_launchers
    launchers.append(result.make_launcher())
                     ~~~~~~~~~~~~~~~~~~~~^^
  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_inductor\runtime\triton_heuristics.py", line 1415, in make_launcher
    self.kernel.load_kernel(device)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_inductor\runtime\static_cuda_launcher.py", line 113, in load_kernel
    (self.function, self.n_regs, self.n_spills) = _StaticCudaLauncher._load_kernel(
                                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self.cubin_path, self.name, self.shared, device
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
torch._inductor.exc.InductorError: RuntimeError: CUDA driver error: file not found

Set TORCHDYNAMO_VERBOSE=1 for the internal stack trace (please do this especially if you're reporting a bug to PyTorch). For even more developer context, set TORCH_LOGS="+dynamo"


2025-08-23T03:43:18.996507 - Prompt executed in 6.51 seconds
2025-08-23T03:43:43.368059 - got prompt
2025-08-23T03:43:43.379134 - WARNING: PlaySound.IS_CHANGED() missing 1 required positional argument: 'self'
2025-08-23T03:43:43.395602 - Using 400 LoRA weight patches for WanVideo model
2025-08-23T03:43:43.458964 - sigmas: tensor([1.0000, 0.9824, 0.9600, 0.9302, 0.8889, 0.8276, 0.7272, 0.5333, 0.0000])
2025-08-23T03:43:43.459186 - Sampling until step 4, timestep: 930
2025-08-23T03:43:43.459969 - timesteps: tensor([999, 982, 959, 930], device='cuda:0')
2025-08-23T03:43:43.460185 - image_cond shape: torch.Size([20, 21, 68, 104])
2025-08-23T03:43:43.890082 - Swapping 10 transformer blocks
2025-08-23T03:43:45.848165 - 
Initializing block swap:  98%|███████████████████████████████████████████████████████▌ | 39/40 [00:01<00:00, 16.77it/s]2025-08-23T03:43:45.915783 - 
Initializing block swap: 100%|█████████████████████████████████████████████████████████| 40/40 [00:02<00:00, 19.76it/s]2025-08-23T03:43:45.916092 - 
2025-08-23T03:43:46.245123 - ----------------------
2025-08-23T03:43:46.245314 - Block swap memory summary:
2025-08-23T03:43:46.246047 - Transformer blocks on cpu: 3352.31MB
2025-08-23T03:43:46.246237 - Transformer blocks on cuda:0: 10056.94MB
2025-08-23T03:43:46.246417 - Total memory used by transformer blocks: 13409.26MB
2025-08-23T03:43:46.246618 - Non-blocking memory transfer: True
2025-08-23T03:43:46.246809 - ----------------------
2025-08-23T03:43:46.247251 - Input sequence length: 37128
2025-08-23T03:43:46.247362 - Sampling 81 frames at 832x544 with 8 steps
2025-08-23T03:43:46.534921 - 
  0%|                                                                                            | 0/4 [00:00<?, ?it/s]2025-08-23T03:43:46.753515 - Error during model prediction: RuntimeError: CUDA driver error: file not found

Set TORCHDYNAMO_VERBOSE=1 for the internal stack trace (please do this especially if you're reporting a bug to PyTorch). For even more developer context, set TORCH_LOGS="+dynamo"

2025-08-23T03:43:49.646626 - 
  0%|                                                                                            | 0/4 [00:03<?, ?it/s]2025-08-23T03:43:49.646750 - 
2025-08-23T03:43:49.647040 - Error during sampling: RuntimeError: CUDA driver error: file not found

Set TORCHDYNAMO_VERBOSE=1 for the internal stack trace (please do this especially if you're reporting a bug to PyTorch). For even more developer context, set TORCH_LOGS="+dynamo"

2025-08-23T03:43:49.987271 - !!! Exception during processing !!! RuntimeError: CUDA driver error: file not found

Set TORCHDYNAMO_VERBOSE=1 for the internal stack trace (please do this especially if you're reporting a bug to PyTorch). For even more developer context, set TORCH_LOGS="+dynamo"

2025-08-23T03:43:50.003005 - Traceback (most recent call last):
  File "E:\Igri\comfyui\ComfyUI\execution.py", line 496, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Igri\comfyui\ComfyUI\execution.py", line 315, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Igri\comfyui\ComfyUI\execution.py", line 289, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "E:\Igri\comfyui\ComfyUI\execution.py", line 277, in process_inputs
    result = f(**inputs)
  File "E:\Igri\comfyui\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\nodes.py", line 3591, in process
    raise e
  File "E:\Igri\comfyui\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\nodes.py", line 3485, in process
    noise_pred, self.cache_state = predict_with_cfg(
                                   ~~~~~~~~~~~~~~~~^
        latent_model_input,
        ^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
        timestep, idx, image_cond, clip_fea, control_latents, vace_data, unianim_data, audio_proj, control_camera_latents, add_cond,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        cache_state=self.cache_state, fantasy_portrait_input=fantasy_portrait_input)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Igri\comfyui\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\nodes.py", line 2610, in predict_with_cfg
    raise e
  File "E:\Igri\comfyui\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\nodes.py", line 2511, in predict_with_cfg
    noise_pred_cond, cache_state_cond = transformer(
                                        ~~~~~~~~~~~^
        [z_pos], context=positive_embeds, y=[image_cond_input] if image_cond_input is not None else None,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
        **base_params
        ^^^^^^^^^^^^^
    )
    ^
  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1773, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1784, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Igri\comfyui\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\wanvideo\modules\model.py", line 2074, in forward
    x, x_ip = block(x, x_ip=x_ip, **kwargs)
              ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_dynamo\eval_frame.py", line 375, in __call__
    return super().__call__(*args, **kwargs)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1773, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1784, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_dynamo\eval_frame.py", line 749, in compile_wrapper
    raise e.remove_dynamo_frames() from None  # see TORCHDYNAMO_VERBOSE=1
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_inductor\compile_fx.py", line 923, in _compile_fx_inner
    raise InductorError(e, currentframe()).with_traceback(
        e.__traceback__
    ) from None
  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_inductor\compile_fx.py", line 907, in _compile_fx_inner
    mb_compiled_graph = fx_codegen_and_compile(
        gm, example_inputs, inputs_to_check, **graph_kwargs
    )
  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_inductor\compile_fx.py", line 1578, in fx_codegen_and_compile
    return scheme.codegen_and_compile(gm, example_inputs, inputs_to_check, graph_kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_inductor\compile_fx.py", line 1456, in codegen_and_compile
    compiled_module = graph.compile_to_module()
  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_inductor\graph.py", line 2293, in compile_to_module
    return self._compile_to_module()
           ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_inductor\graph.py", line 2303, in _compile_to_module
    mod = self._compile_to_module_lines(wrapper_code)
  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_inductor\graph.py", line 2371, in _compile_to_module_lines
    mod = PyCodeCache.load_by_key_path(
        key,
    ...<2 lines>...
        attrs={**self.constants, **self.torchbind_constants},
    )
  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_inductor\codecache.py", line 3296, in load_by_key_path
    mod = _reload_python_module(key, path, set_sys_modules=in_toplevel)
  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_inductor\runtime\compile_tasks.py", line 31, in _reload_python_module
    exec(code, mod.__dict__, mod.__dict__)
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Temp\torchinductor_user123\k4\ck4aty3soay34puqlm5phdtjqapxreymgqhgpo3top46llmgcie5.py", line 55, in <module>
  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_inductor\async_compile.py", line 404, in triton
    kernel.precompile(
    ~~~~~~~~~~~~~~~~~^
        warm_cache_only=False,
        ^^^^^^^^^^^^^^^^^^^^^^
        static_triton_bundle_key=CompiledTritonKernels.key(source_code),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_inductor\runtime\triton_heuristics.py", line 411, in precompile
    self._make_launchers()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_inductor\runtime\triton_heuristics.py", line 568, in _make_launchers
    launchers.append(result.make_launcher())
                     ~~~~~~~~~~~~~~~~~~~~^^
  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_inductor\runtime\triton_heuristics.py", line 1415, in make_launcher
    self.kernel.load_kernel(device)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "E:\Igri\comfyui\python_embeded\Lib\site-packages\torch\_inductor\runtime\static_cuda_launcher.py", line 113, in load_kernel
    (self.function, self.n_regs, self.n_spills) = _StaticCudaLauncher._load_kernel(
                                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self.cubin_path, self.name, self.shared, device
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
torch._inductor.exc.InductorError: RuntimeError: CUDA driver error: file not found

Set TORCHDYNAMO_VERBOSE=1 for the internal stack trace (please do this especially if you're reporting a bug to PyTorch). For even more developer context, set TORCH_LOGS="+dynamo"


2025-08-23T03:43:50.017829 - Prompt executed in 6.64 seconds

```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
Workflow too large. Please manually upload the workflow from local file system.
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

**Comment by kijai** [comment]
You don't have a working Triton installation so torch.compile doesn't work, you can disable that by disconnecting the compile_args from the model loader.

**Comment by GolovanPriherel** [comment]
> You don't have a working Triton installation so torch.compile doesn't work, you can disable that by disconnecting the compile_args from the model loader.

Oh yeah, now everything works! As you said, I disabled the "compile_args" link and everything started working.

Thank you very much, it seems that you are my personal guardian angel in the world of comfyui and everything connected with it. I spent 3 whole days trying all possible ways to solve this problem and I did not want to bother anyone in vain.

Thank you again for your help, I am really looking forward to Wan 2.2 Vace performed by you!

**Comment by DASHU0126** [comment]
> > You don't have a working Triton installation so torch.compile doesn't work, you can disable that by disconnecting the compile_args from the model loader.
> 
> Oh yeah, now everything works! As you said, I disabled the "compile_args" link and everything started working.
> 
> Thank you very much, it seems that you are my personal guardian angel in the world of comfyui and everything connected with it. I spent 3 whole days trying all possible ways to solve this problem and I did not want to bother anyone in vain.
> 
> Thank you again for your help, I am really looking forward to Wan 2.2 Vace performed by you!

hi，so how to  disabled the "compile_args" link？
