### ISSUE TITLE
ONNXRuntimeError

### ISSUE THREAD

**Issue by CKay010** [kijai/ComfyUI-WanVideoWrapper#1353]
[ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running QuickGelu node. Name:'/model.0/act/Mul/QuickGeluFusion/' Status Message: CUDA error cudaErrorNoKernelImageForDevice:no kernel image is available for execution on the device

RTX5090 trying to use wan animate new update V2 with example 02 workflow

**Comment by kijai** [comment]
Something wrong with your onnx install, I'd try updating/re-install `onnx` and `onnxruntime-gpu`.

**Comment by CHKE9** [comment]
> Something wrong with your onnx install, I'd try updating/re-install `onnx` and `onnxruntime-gpu`.

i did upgrade to 1.23.0 still getting the same error

**Comment by CHKE9** [comment]
onnx                 1.19.0
onnxruntime          1.23.0
onnxruntime-gpu      1.23.0

**Comment by lubiteltv** [comment]
I am getting the same error with a 5090, same V2 workflow...


[ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running QuickGelu node. Name:'/model.0/act/Mul/QuickGeluFusion/' Status Message: CUDA error cudaErrorNoKernelImageForDevice:no kernel image is available for execution on the device

**Comment by ohhhyy** [comment]
same issue with 5060ti, v2 workflow too

LynxInsightFaceCrop
[ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Relu node. Name:'Relu_2' Status Message: CUDA error cudaErrorInvalidPtx:a PTX JIT compilation failed

**Comment by CharlieDreemur** [comment]
same issue with 5090, when using [wanvideo_T2V_14B_lynx_example_01.json](https://github.com/kijai/ComfyUI-WanVideoWrapper/commit/a088425268d34f7ca0be96c078db2b63f03ca012)

**Comment by CharlieDreemur** [comment]
I fix it, by installing 1.22.0 onnxruntime-gpu instead of 1.23.0
```bash
pip uninstall -y onnxruntime-gpu
pip install "onnxruntime-gpu==1.22.0"
```

**Comment by ohhhyy** [comment]
> I fix it, by installing 1.22.0 onnxruntime-gpu instead of 1.23.0
> 
> pip uninstall -y onnxruntime-gpu
> pip install "onnxruntime-gpu==1.22.0"

thx,works for me

**Comment by lubiteltv** [comment]
I did many shenanigans too and it now works for me too...

**Comment by CHKE9** [comment]
do

> I fix it, by installing 1.22.0 onnxruntime-gpu instead of 1.23.0
> 
> pip uninstall -y onnxruntime-gpu
> pip install "onnxruntime-gpu==1.22.0"

doesnt work for me :/

**Comment by divyata3d** [comment]
Hi,
I have got same issue with 5090 and i am new about this. so can some one explain here how to run above command step by step. It's so help for me.

**Comment by RuneGjerde** [comment]
> Hi, I have got same issue with 5090 and i am new about this. so can some one explain here how to run above command step by step. It's so help for me.

Assuming you are on ComfyUI portable (or desktop version) if you are all new to this, and on Windows. 
Open the comfyUI folder and then open command window (easiest way is to write CMD at Windows Explorer "address field" at top of the explorer window, that makes windows terminal/command window be at same folder location)

`\python_embeded\python.exe -m pip install [package_name]`

and replace _package_name_ with what you want to install..  "onnxruntime-gpu==1.22.0"  I guess in this case

**Comment by divyata3d** [comment]
> > Hi, I have got same issue with 5090 and i am new about this. so can some one explain here how to run above command step by step. It's so help for me.
> 
> Assuming you are on ComfyUI portable (or desktop version) if you are all new to this, and on Windows. Open the comfyUI folder and then open command window (easiest way is to write CMD at Windows Explorer "address field" at top of the explorer window, that makes windows terminal/command window be at same folder location)
> 
> `\python_embeded\python.exe -m pip install [package_name]`
> 
> and replace _package_name_ with what you want to install.. "onnxruntime-gpu==1.22.0" I guess in this case

Hi, RuneGjerde
Now It's working, Thank you so much

**Comment by stockarea** [comment]
[ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running QuickGelu node. Name:'/model.0/act/Mul/QuickGeluFusion/' Status Message: CUDA error cudaErrorNoKernelImageForDevice:no kernel image is available for execution on the device

I am also getting this error....

**Comment by CHKE9** [comment]
> [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running QuickGelu node. Name:'/model.0/act/Mul/QuickGeluFusion/' Status Message: CUDA error cudaErrorNoKernelImageForDevice:no kernel image is available for execution on the device
> 
> I am also getting this error....

try changing onnx versions to older as above said

**Comment by stockarea** [comment]
I tried doing both 1.22 and 1.23.. getting error in both
