### ISSUE TITLE
KiJai,Is it possible to reduce the memory usage  when use LoRA?

### ISSUE THREAD

**Issue by dummyapps** [kijai/ComfyUI-WanVideoWrapper#263]
My PC:
4060Ti 16G, 64G ram, enable wanvideo vram management, teacache , slg,  enhance-a-video.
Model: wan2.1 i2v 720p 14b fp16, base precision: fp16 ,quantization: disabled, vae tiling: enabled

Without lora: 
Vram: about 6G, Ram: 52G, works well

With Lora:
Vram: about 6G, Ram: 61G, ComfyUI always crash because of out of memory when execute WanVideo Decode node

Is it possible to reduce the memory usage  when use LoRA?

**Comment by kijai** [comment]
> My PC: 4060Ti 16G, 64G ram, enable wanvideo vram management, teacache , slg, enhance-a-video. Model: wan2.1 i2v 720p 14b fp16, base precision: fp16 ,quantization: disabled, vae tiling: enabled
> 
> Without lora: Vram: about 6G, Ram: 52G, works well
> 
> With Lora: Vram: about 6G, Ram: 61G, ComfyUI always crash because of out of memory when execute WanVideo Decode node
> 
> Is it possible to reduce the memory usage when use LoRA?

That sounds weird, it should not affect the VAE decode... does it work if the VAE tiling is enabled?

**Comment by dummyapps** [comment]
VAE tiling is always enabled.

when load Lora, if I use 720P_14B_bf16 and enable quantization, it works well, but if I use 720P_14B_fp16 and enable quantization, ComfyUI will crash when execute WanVideo Decode node.

**Comment by kijai** [comment]
I don't really understand how that could be, fp16 is the recommended one anyway btw.

You could try disabling the non-blocking transfers if you are using the block swapping node, this sounds like RAM issue more than VRAM... assuming you are using force_offload on the sampler.

**Comment by sd2530615** [comment]
how did you run wan2.1 i2v 720p 14b but only consuming 6G Vram?

**Comment by dummyapps** [comment]
> I don't really understand how that could be, fp16 is the recommended one anyway btw.
> 
> You could try disabling the non-blocking transfers if you are using the block swapping node, this sounds like RAM issue more than VRAM... assuming you are using force_offload on the sampler.

thank you very much, Kijai, after tried many time, I set virtual memory of win11 up to 50G, and set offload percent of WanVideo VRAM management to 0.7, it works very well.

**Comment by dummyapps** [comment]
> how did you run wan2.1 i2v 720p 14b but only consuming 6G Vram?

I use KiJai's I2V workflow, and use WanVideo VRAM management node to manage Vram, when offload percent set to 1.0, 720P_14B_fp16 only consuming 6G Vram, but it needs very large Ram.

**Comment by 3dluvr** [comment]
Isn't that painfully slow at 0.7-1.0 offload - how many s/it do you get with a 4060Ti?

**Comment by swisspol** [comment]
I have the same issue: using a LORA uses a lot more VRAM.

120 GB RAM
nVidia H100 w/ 80 GB RAM

WanVideoWrapper version: 5a2383621a05825d0d0437781afcb8552d9590fd

Without the Lora, about 72% RAM is used. With the Lora is increases to 99% then fails when starting sampling (OOM error).

I tried changing all sort of settings (e.g. low_mem_load for the Lora), using BlockSwap or VRAM management, but no success: always OOM.

_Note that I can use the Lora without any problem with the native ComfyUI Wan nodes._

Here's my setup:
![Image](https://github.com/user-attachments/assets/f9c8bea2-2d31-4d3c-87c3-4809b68365ab)

```
Model type: i2v, num_heads: 40, num_layers: 40
Model variant detected: i2v_720
TeaCache: Using cache device: cuda:0
model_type FLOW
Using accelerate to load and assign model weights to device...
Loading transformer parameters to cuda:0: 100%|██████████| 1303/1303 [00:00<00:00, 27033.79it/s]
Loading LoRA: wan/rotate_20_epochs with strength: 1.0
Loading model and applying LoRA weights:: 100%|██████████| 731/731 [00:00<00:00, 2558.10it/s]
image_cond torch.Size([20, 21, 160, 90])
Seq len: 75600
previewer:  None
Sampling 81 frames at 720x1280 with 25 steps
  0%|          | 0/25 [00:00<?, ?it/s]
!!! Exception during processing !!! Allocation on device 
Traceback (most recent call last):
  File "/opt/ComfyUI/execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/ComfyUI/execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/ComfyUI/execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/opt/ComfyUI/execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/ComfyUI/custom_nodes/ComfyUI-WanVideoWrapper/nodes.py", line 2074, in process
    noise_pred, self.teacache_state = predict_with_cfg(
                                      ^^^^^^^^^^^^^^^^^
  File "/opt/ComfyUI/custom_nodes/ComfyUI-WanVideoWrapper/nodes.py", line 1793, in predict_with_cfg
    noise_pred_cond, teacache_state_cond = transformer(
                                           ^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/ComfyUI/custom_nodes/ComfyUI-WanVideoWrapper/wanvideo/modules/model.py", line 859, in forward
    x = block(x, **kwargs)
        ^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 465, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/ComfyUI/custom_nodes/ComfyUI-WanVideoWrapper/wanvideo/modules/model.py", line 410, in forward
    def forward(
  File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/ComfyUI/custom_nodes/ComfyUI-WanVideoWrapper/wanvideo/modules/model.py", line 224, in forward
    def forward(self, x, seq_lens, grid_sizes, freqs, rope_func = "default"):
  File "/opt/conda/lib/python3.11/site-packages/torch/amp/autocast_mode.py", line 44, in decorate_autocast
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/ComfyUI/custom_nodes/ComfyUI-WanVideoWrapper/wanvideo/modules/model.py", line 108, in rope_apply
    x_i = view_as_complex_no_compile(x)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 632, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/ComfyUI/custom_nodes/ComfyUI-WanVideoWrapper/wanvideo/modules/model.py", line 105, in view_as_complex_no_compile
    x_i = torch.view_as_complex(x[i, :seq_len].to(torch.float64).reshape(seq_len, n, -1, 2))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.OutOfMemoryError: Allocation on device 

Got an OOM, unloading all loaded models.
Prompt executed in 4.72 seconds
```

**Comment by kijai** [comment]
Not sure why that would happen, haven't noticed it myself.. but seeing that error is from the RoPE function you could try using the "comfy" RoPE instead here:

![Image](https://github.com/user-attachments/assets/fedb8452-c7cc-4305-9919-7553c620b52a)

Especially with torch.compile it uses less memory and is faster in general, with minimal impact on the results, which is not to say even to worse... just slightly different from the original.

**Comment by kijai** [comment]
Oh and I _really_ don't see how it can possibly even fill 80GB? What resolution is that? I can do 81 frames at 1280x768 with full offloading just by 24GB VRAM and within 128GB RAM using the model at fp16.

You don't happen to have `--high-vram` in comfy startup args? That would make all the "offload_devices" to GPU. Note that also in native Comfy it does offloading automatically if necessary, here it's behind the block swap -feature.

**Comment by swisspol** [comment]
Same issue with `rope_function` set to Comfy (I also tried enabling `low_mem_load` on the lora as well as setting VRAM Management to 1.0):

```
got prompt
image_cond torch.Size([20, 21, 160, 90])
Seq len: 75600
previewer:  None
Sampling 81 frames at 720x1280 with 25 steps
  0%|          | 0/25 [00:00<?, ?it/s]
!!! Exception during processing !!! Allocation on device 
Traceback (most recent call last):
  File "/opt/ComfyUI/execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/ComfyUI/execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/ComfyUI/execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/opt/ComfyUI/execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/ComfyUI/custom_nodes/ComfyUI-WanVideoWrapper/nodes.py", line 2074, in process
    noise_pred, self.teacache_state = predict_with_cfg(
                                      ^^^^^^^^^^^^^^^^^
  File "/opt/ComfyUI/custom_nodes/ComfyUI-WanVideoWrapper/nodes.py", line 1793, in predict_with_cfg
    noise_pred_cond, teacache_state_cond = transformer(
                                           ^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/ComfyUI/custom_nodes/ComfyUI-WanVideoWrapper/wanvideo/modules/model.py", line 859, in forward
    x = block(x, **kwargs)
        ^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 465, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/ComfyUI/custom_nodes/ComfyUI-WanVideoWrapper/wanvideo/modules/model.py", line 410, in forward
    def forward(
  File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/ComfyUI/custom_nodes/ComfyUI-WanVideoWrapper/wanvideo/modules/model.py", line 224, in forward
    def forward(self, x, seq_lens, grid_sizes, freqs, rope_func = "default"):
  File "/opt/conda/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 632, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/_functorch/aot_autograd.py", line 1100, in forward
    return compiled_fn(full_args)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 321, in runtime_wrapper
    all_outs = call_func_at_runtime_with_args(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/_functorch/_aot_autograd/utils.py", line 124, in call_func_at_runtime_with_args
    out = normalize_as_list(f(args))
                            ^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 667, in inner_fn
    outs = compiled_fn(args)
           ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 488, in wrapper
    return compiled_fn(runtime_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/codecache.py", line 1478, in __call__
    return self.current_callable(inputs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/utils.py", line 1977, in run
    return model(new_inputs)
           ^^^^^^^^^^^^^^^^^
  File "/tmp/torchinductor_root/2d/c2dmaywokve7q37nlasjgptjmvjinw6ubowoictcqqqqj646mkop.py", line 254, in call
    buf9 = empty_strided_cuda((1, 75600, 40, 128), (387072000, 5120, 128, 1), torch.bfloat16)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.OutOfMemoryError: Allocation on device 

Got an OOM, unloading all loaded models.
Prompt executed in 0.31 seconds
```

**Comment by swisspol** [comment]
> Oh and I _really_ don't see how it can possibly even fill 80GB? What resolution is that? I can do 81 frames at 1280x768 with full offloading just by 24GB VRAM and within 128GB RAM using the model at fp16.

1280x720

> You don't happen to have `--high-vram` in comfy startup args? That would make all the "offload_devices" to GPU. Note that also in native Comfy it does offloading automatically if necessary, here it's behind the block swap -feature.

I'm running Comfy with `--high-vram` indeed. In my experience, it seems to make running workflows faster as it seems to keep more stuff in VRAM.

Should I change some of the `load_device` settings from `offload_device` to something else in some of the nodes? Sorry, not familiar with device management yet.

**Comment by swisspol** [comment]
It works now when running ComfyUI without `--high-vram`. Thanks for the help! VRAM usage is around 55% during sampling.

**Comment by kijai** [comment]
> It works now when running ComfyUI without `--high-vram`. Thanks for the help! VRAM usage is around 55% during sampling.

--high-vram just changes the "offload_device" in general in comfy to GPU from CPU, I suppose I should probably change from using that to just plain use CPU always since I have the choice in the node anyway... or to add CPU as option to override any command line arguments.

**Comment by swisspol** [comment]
For reference, there's already an open issue at #196 touching on these very topics of `--high-vram` and loras.

**Comment by dummyapps** [comment]
> Isn't that painfully slow at 0.7-1.0 offload - how many s/it do you get with a 4060Ti?

from 50s/it to 25s/it, 576x1024 720p 14b fp16, 29frames, total about 10min
