### ISSUE TITLE
CUDA error: invalid argument

### ISSUE THREAD

**Issue by andypotato** [kijai/ComfyUI-WanVideoWrapper#270]
Using the example I2V workflow I receive the following error:

**(Possible solution suggested after the error log)**

```
  0%|                                                                                                                             | 0/25 [00:02<?, ?it/s]
!!! Exception during processing !!! CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Traceback (most recent call last):
  File "/media/data/SD/ComfyUI/execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/SD/ComfyUI/execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/SD/ComfyUI/execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/media/data/SD/ComfyUI/execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/SD/ComfyUI/custom_nodes/ComfyUI-WanVideoWrapper/nodes.py", line 1909, in process
    noise_pred, self.teacache_state = predict_with_cfg(
                                      ^^^^^^^^^^^^^^^^^
  File "/media/data/SD/ComfyUI/custom_nodes/ComfyUI-WanVideoWrapper/nodes.py", line 1628, in predict_with_cfg
    noise_pred_cond, teacache_state_cond = transformer(
                                           ^^^^^^^^^^^^
  File "/home/mars/miniconda3/envs/comfyenv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mars/miniconda3/envs/comfyenv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/SD/ComfyUI/custom_nodes/ComfyUI-WanVideoWrapper/wanvideo/modules/model.py", line 862, in forward
    block.to(self.offload_device, non_blocking=self.use_non_blocking)
  File "/home/mars/miniconda3/envs/comfyenv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1343, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/mars/miniconda3/envs/comfyenv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 903, in _apply
    module._apply(fn)
  File "/home/mars/miniconda3/envs/comfyenv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 903, in _apply
    module._apply(fn)
  File "/home/mars/miniconda3/envs/comfyenv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 930, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "/home/mars/miniconda3/envs/comfyenv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1329, in convert
    return t.to(
           ^^^^^
RuntimeError: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

The error seems to originate from `custom_nodes/ComfyUI-WanVideoWrapper/wanvideo/modules/model.py` around line 861:

```
block.to(self.offload_device, non_blocking=self.use_non_blocking)
```

I added debug code to output the `offload_device` and whether or not `non_blocking` is used:
```
print("Moving block to:", self.offload_device, "with non_blocking =", self.use_non_blocking)
block.to(self.offload_device, non_blocking=self.use_non_blocking)
```

The log output before the crash is:
```
Moving block to: cpu with non_blocking = True
```

Now to my knowledge, In PyTorch, non-blocking transfers only work when moving data between pinned CPU memory and a GPU. When transferring data to the CPU, the non-blocking flag must be set to False. Maybe this has changed in more recent PyTorch versions.

I modified the code the following way and it is now working again:

```
non_blocking_flag = self.use_non_blocking if self.offload_device.type == "cuda" else False
block.to(self.offload_device, non_blocking=non_blocking_flag)
```

The issue may have been introduced with this commit: https://github.com/kijai/ComfyUI-WanVideoWrapper/commit/81a08d0e59922a54797e9a400c73d26b5be7db6d

Thoughts?

**Comment by andypotato** [comment]
looking at the commit referenced above, setting "use_non_blocking" to `false` will also fix the issue

**Comment by kijai** [comment]
It's always been working for me when going from GPU -> CPU and it's a bit faster, it does hold more RAM probably because of the pinned memory? I'm no expert with any of that and pytorch RAM management still baffles me, all I know is that use_non_blocking=True when going to offload_device makes it faster for me.
