### ISSUE TITLE
Is the error 'CUDA error: CUBLAS_STATUS_NOT_SUPPORTED' caused by my use of CUDA 11.8, or is CUDA 12 or higher required?

### ISSUE THREAD

**Issue by tangerdream** [kijai/ComfyUI-WanVideoWrapper#50]
Request for help, with the specific error message as follows:

!!! Exception during processing !!! CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasLtMatmulAlgoGetHeuristic( ltHandle, computeDesc.descriptor(), Adesc.descriptor(), Bdesc.descriptor(), Cdesc.descriptor(), Ddesc.descriptor(), preference.descriptor(), 1, &heuristicResult, &returnedResult)`
Traceback (most recent call last):
  File "/home/ml/tanghc/ComfyUI/execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ml/tanghc/ComfyUI/execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ml/tanghc/ComfyUI/execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/home/ml/tanghc/ComfyUI/execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ml/tanghc/ComfyUI/custom_nodes/ComfyUI-WanVideoWrapper/nodes.py", line 976, in process
    noise_pred_cond = transformer(
                      ^^^^^^^^^^^^
  File "/home/ml/anaconda3/envs/cf311/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ml/anaconda3/envs/cf311/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ml/tanghc/ComfyUI/custom_nodes/ComfyUI-WanVideoWrapper/wanvideo/modules/model.py", line 576, in forward
    context = self.text_embedding(
              ^^^^^^^^^^^^^^^^^^^^
  File "/home/ml/anaconda3/envs/cf311/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ml/anaconda3/envs/cf311/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ml/anaconda3/envs/cf311/lib/python3.11/site-packages/torch/nn/modules/container.py", line 250, in forward
    input = module(input)
            ^^^^^^^^^^^^^
  File "/home/ml/anaconda3/envs/cf311/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ml/anaconda3/envs/cf311/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ml/tanghc/ComfyUI/custom_nodes/ComfyUI-WanVideoWrapper/fp8_optimization.py", line 39, in <lambda>
    setattr(module, "forward", lambda input, m=module: fp8_linear_forward(m, original_dtype, input))
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ml/tanghc/ComfyUI/custom_nodes/ComfyUI-WanVideoWrapper/fp8_optimization.py", line 18, in fp8_linear_forward
    o = torch._scaled_mm(inn, w, out_dtype=original_dtype, bias=bias, scale_a=scale, scale_b=scale)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasLtMatmulAlgoGetHeuristic( ltHandle, computeDesc.descriptor(), Adesc.descriptor(), Bdesc.descriptor(), Cdesc.descriptor(), Ddesc.descriptor(), preference.descriptor(), 1, &heuristicResult, &returnedResult)`

**Comment by singlinhaha** [comment]
same problem by my use of CUDA 11.8.

**Comment by kijai** [comment]
Fp8_fast at least does require newer CUDA, it doesn't really work well currently anyway with this model, has a huge quality hit. Normal fp8 mode works ok, does that work for you?

**Comment by singlinhaha** [comment]
It is work!!! thanks！

**Comment by tangerdream** [comment]
> It is work!!! thanks！  这是工作！！！谢谢！


How did you manage to do that? I have not found the option to switch between Fp8_fast and Normal fp8 mode.

**Comment by tangerdream** [comment]
![Image](https://github.com/user-attachments/assets/b0598b49-77e3-4e2d-aca1-7b852a6ec692)
Ok，i got it。 Thanks

**Comment by singlinhaha** [comment]
![Image](https://github.com/user-attachments/assets/4173470e-c579-457f-a632-1fef9f9063fb)

**Comment by drding1987** [comment]
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by tangerdream** [comment]
> RuntimeError: CUDA error: no kernel image is available for execution on the device CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1 Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Yeah, so was I. So i have switched to Cuda12, and it worked.
