### ISSUE TITLE
Out of memory on 4090 with VACE 14b

### ISSUE THREAD

**Issue by jnpatrick99** [kijai/ComfyUI-WanVideoWrapper#562]
I tried Wan 14b i2v and Wan VACE 14b module on 24GB VRAM and it gives me out of memory error. I tried setting quantization to fp8 and it didn't help. How much VRAM does this need?

**Comment by cheezecrisp** [comment]
Why don't you use blockswap?

**Comment by kijai** [comment]
Need to use block swap indeed, when swapping even single block the VACE temporary outputs are also offloaded, this leads to pretty big VRAM saving. It will easily fit 24GB for 720p 81 frames with enough blocks swapped.

**Comment by jnpatrick99** [comment]
@kijai Thanks! 
That worked at VRAM 89% but using it produced invalid image - green noise slightly based on input image (I can see some moving shapes and everything looks extremely pixelated).

Trying on 480p btw, 81 frames.
vace_model: Wan2_1-VACE_module_14B_fp8_e4m3fn
WanVideo model: wan2.1_i2v_480p_14B_fp8_e4m3fn - this worked with VACE 1.3B
quantization: fp8_e4m3fn
base_precision: bf16
attention: sageattn
VAE: Wan2_1_VAE_bf16
T5 precision: bf16
T5 quantization: fp8_e4m3fn
WanVideo BlockSwap: 15/false/false/true/15

**Comment by kijai** [comment]
> [@kijai](https://github.com/kijai) Thanks! That worked at VRAM 89% but using it produced invalid image - green noise slightly based on input image (I can see some moving shapes and everything looks extremely pixelated).
> 
> Trying on 480p btw, 81 frames. vace_model: Wan2_1-VACE_module_14B_fp8_e4m3fn WanVideo model: wan2.1_i2v_480p_14B_fp8_e4m3fn - this worked with VACE 1.3B quantization: fp8_e4m3fn base_precision: bf16 attention: sageattn VAE: Wan2_1_VAE_bf16 T5 precision: bf16 T5 quantization: fp8_e4m3fn WanVideo BlockSwap: 15/false/false/true/15

You need to pair VACE with T2V model, not I2V.

**Comment by jnpatrick99** [comment]
Oh so cool, thank you that fixed it

**Comment by jnpatrick99** [comment]
Is there a way to improve speed when using blockswap? It becomes 4hrs 30 min for 350 frames (only around 40 minutes when using 1.3B).
