### ISSUE TITLE
4090 ,out of memory

### ISSUE THREAD

**Issue by juzi260** [kijai/ComfyUI-WanVideoWrapper#565]
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by juzi260** [comment]
![Image](https://github.com/user-attachments/assets/0e9b5ef2-ed22-42e3-b689-7fe0f453e0d8)

**Comment by juzi260** [comment]
[ComfyUI-Manager] All startup tasks have been completed.
Exception in thread Thread-23 (prompt_worker):
Traceback (most recent call last):
  File "C:\ComfyUI-aki-v1.6\ComfyUI\execution.py", line 349, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI-aki-v1.6\ComfyUI\execution.py", line 224, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI-aki-v1.6\ComfyUI\execution.py", line 196, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\ComfyUI-aki-v1.6\ComfyUI\execution.py", line 185, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI-aki-v1.6\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\nodes.py", line 3236, in process
    noise_pred, self.teacache_state = predict_with_cfg(
                                      ^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI-aki-v1.6\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\nodes.py", line 2870, in predict_with_cfg
    noise_pred_cond, teacache_state_cond = transformer(
                                           ^^^^^^^^^^^^
  File "C:\ComfyUI-aki-v1.6\python\Lib\site-packages\torch\nn\modules\module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI-aki-v1.6\python\Lib\site-packages\torch\nn\modules\module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI-aki-v1.6\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\wanvideo\modules\model.py", line 1426, in forward
    block.to(self.offload_device, non_blocking=self.use_non_blocking)
  File "C:\ComfyUI-aki-v1.6\python\Lib\site-packages\torch\nn\modules\module.py", line 1343, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI-aki-v1.6\python\Lib\site-packages\torch\nn\modules\module.py", line 903, in _apply
    module._apply(fn)
  File "C:\ComfyUI-aki-v1.6\python\Lib\site-packages\torch\nn\modules\module.py", line 903, in _apply
    module._apply(fn)
  File "C:\ComfyUI-aki-v1.6\python\Lib\site-packages\torch\nn\modules\module.py", line 930, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "C:\ComfyUI-aki-v1.6\python\Lib\site-packages\torch\nn\modules\module.py", line 1329, in convert
    return t.to(
           ^^^^^
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ComfyUI-aki-v1.6\python\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "<enhanced_experience vendors.sentry_sdk.integrations.threading>", line 99, in run
  File "<enhanced_experience vendors.sentry_sdk.integrations.threading>", line 94, in _run_old_run_func
  File "<enhanced_experience vendors.sentry_sdk.utils>", line 1649, in reraise
  File "<enhanced_experience vendors.sentry_sdk.integrations.threading>", line 92, in _run_old_run_func
  File "C:\ComfyUI-aki-v1.6\python\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ComfyUI-aki-v1.6\ComfyUI\main.py", line 176, in prompt_worker
    e.execute(item[2], prompt_id, item[3], item[4])
  File "C:\ComfyUI-aki-v1.6\ComfyUI\execution.py", line 527, in execute
    result, error, ex = execute(self.server, dynamic_prompt, self.caches, node_id, extra_data, executed, prompt_id, execution_list, pending_subgraph_results)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI-aki-v1.6\ComfyUI\execution.py", line 416, in execute
    input_data_formatted[name] = [format_value(x) for x in inputs]
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI-aki-v1.6\ComfyUI\execution.py", line 416, in <listcomp>
    input_data_formatted[name] = [format_value(x) for x in inputs]
                                  ^^^^^^^^^^^^^^^
  File "C:\ComfyUI-aki-v1.6\ComfyUI\execution.py", line 268, in format_value
    return str(x)
           ^^^^^^
  File "C:\ComfyUI-aki-v1.6\python\Lib\site-packages\torch\_tensor.py", line 568, in __repr__
    return torch._tensor_str._str(self, tensor_contents=tensor_contents)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI-aki-v1.6\python\Lib\site-packages\torch\_tensor_str.py", line 704, in _str
    return _str_intern(self, tensor_contents=tensor_contents)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI-aki-v1.6\python\Lib\site-packages\torch\_tensor_str.py", line 621, in _str_intern
    tensor_str = _tensor_str(self, indent)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI-aki-v1.6\python\Lib\site-packages\torch\_tensor_str.py", line 353, in _tensor_str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI-aki-v1.6\python\Lib\site-packages\torch\_tensor_str.py", line 391, in get_summarized_data
    return torch.stack([get_summarized_data(x) for x in self])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI-aki-v1.6\python\Lib\site-packages\torch\_tensor_str.py", line 391, in <listcomp>
    return torch.stack([get_summarized_data(x) for x in self])
                        ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI-aki-v1.6\python\Lib\site-packages\torch\_tensor_str.py", line 379, in get_summarized_data
    return torch.cat(
           ^^^^^^^^^^
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

got prompt

**Comment by kijai** [comment]
Out the RAM, reduce the block swap amount or disable the non_blocking in the block swap node.

**Comment by juzi260** [comment]
The problem is solved, thank you very much！！
