### ISSUE TITLE
It doesn't look like it's swapping?

### ISSUE THREAD

**Issue by juanml82** [kijai/ComfyUI-WanVideoWrapper#653]
No matter how many blocks I indicate to swap, it's performing in the same way: everything goes into vram and I get an OOM error. This is the console output
got prompt
encoded latents shape torch.Size([1, 16, 9, 64, 64])
!!! Exception during processing !!! Allocation on device 
Traceback (most recent call last):
  File "/mnt/shared/ComfyUI/execution.py", line 349, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/shared/ComfyUI/execution.py", line 224, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/shared/ComfyUI/execution.py", line 196, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/mnt/shared/ComfyUI/execution.py", line 185, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/shared/ComfyUI/custom_nodes/ComfyUI-WanVideoWrapper/nodes.py", line 591, in loadmodel
    sd = load_torch_file(model_path, device=transformer_load_device, safe_load=True)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/shared/ComfyUI/comfy/utils.py", line 71, in load_torch_file
    raise e
  File "/mnt/shared/ComfyUI/comfy/utils.py", line 61, in load_torch_file
    sd[k] = f.get_tensor(k)
            ^^^^^^^^^^^^^^^
torch.OutOfMemoryError: Allocation on device 

Got an OOM, unloading all loaded models.
Prompt executed in 7.53 seconds
And this is a capture of how I'm using the workflow

![Image](https://github.com/user-attachments/assets/64a083a3-271d-4539-adef-1903270f925d)

My hardware is a ryzen 5 3600 with 32gb of system ram (2x16 not of the same brand) and an RTX 3090. I'm not sure what additional information I could add for troubleshooting

**Comment by kijai** [comment]
The swapping happens during sampling, on the loader the block setting has no effect. It should be loading to RAM at that point with offload_device selected. You aren't running with something like --high-vram selected? That would change offload_device to GPU and potentially explain this.

**Comment by juanml82** [comment]
Ahh, yes, I was using --high-vram. I started it again without it and it's now working
