### ISSUE TITLE
OOM on GPU for 64GB system memory with Nvidia 24GB VRAM on Google Cloud

### ISSUE THREAD

**Issue by unjadded** [kijai/ComfyUI-WanVideoWrapper#752]
Trying WAN VACE 2.1 using some basic settings on my GCP instance. I have plenty of system memory and GPU is Nvidia 24GB. 

- 14B param model, fp16
- enabled low mem load for the Lora
- Nvidia L4 24GB
- 16 cores 64GB system memory
- Dies during WanVideo Sampler stage
- block swap 10
- vace swap 7
- sageattn mode
- offload device for the T2V loading part
- bf16 text encoder (heard maybe fp16 is better here?)
- frame rate 20
- launched with --normalvram (maybe this is the mistake?)
- 

Very odd considering I had it running once on the 48GB system memory. GPU memory craps out here.

  File "/mnt/comfyui_data/comfy/ComfyUI/custom_nodes/ComfyUI-WanVideoWrapper/wanvideo/modules/model.py", line 768, in forward
    c = super().forward(c, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/comfyui_data/comfy/ComfyUI/custom_nodes/ComfyUI-WanVideoWrapper/wanvideo/modules/model.py", line 633, in forward
    y, x_ref_attn_map = self.self_attn.forward(
                        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/comfyui_data/comfy/ComfyUI/custom_nodes/ComfyUI-WanVideoWrapper/wanvideo/modules/model.py", line 252, in forward
    q, k = apply_rope_comfy(q, k, freqs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/comfyui_data/comfy/ComfyUI/comfy/ldm/flux/math.py", line 42, in apply_rope
    xq_out = freqs_cis[..., 0] * xq_[..., 0] + freqs_cis[..., 1] * xq_[..., 1]
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
torch.OutOfMemoryError: Allocation on device

Got an OOM, unloading all loaded models.


Not sure what i need to tweak

**Comment by unjadded** [comment]
Weird because the GPU doesn't even max out on monitoring...

<img width="1368" height="506" alt="Image" src="https://github.com/user-attachments/assets/8b58bd7e-445c-4a87-a135-3e8cb5943586" />

**Comment by kijai** [comment]
What resolution? And the 48gb is on single card? That does indeed look like the usual out if VRAM error, can always try to increase block swap, though 48gb should be enough even without.

**Comment by unjadded** [comment]
Sorry Kijai, my message confused you.

The OP says 24GB ram. Ignore the 48GB system memory comment. This is for 720P

I got it working after increasing block swap size just barely as system memory capped out at 92% and NVRAM was also 93%.

Once the video finished, the Image Combiner node failed (where it stitches the control image with the reference image and shows a preview side by side). I disabled this specific combiner node to prevent crashing in the end.

Now it fails again with a 5mb reference video for the WAN VACE model. Attached some of my settings. Going to rerun with block swap of 30 instead of 25..

<img width="695" height="553" alt="Image" src="https://github.com/user-attachments/assets/76ed1c44-43d5-415f-9ee8-aa3fa08c2438" />

<img width="631" height="513" alt="Image" src="https://github.com/user-attachments/assets/bce930af-db10-4e8c-a4cd-18bf29d3c21d" />

**Comment by unjadded** [comment]
Looks like system memory this time failed, not VRAM. Which is crazy because I have 61GB of free system memory.

'''
Florence2 using sdpa for attention
<unknown>:515: SyntaxWarning: invalid escape sequence '\d'
Offloading model...
Detected model in_channels: 16
Model type: t2v, num_heads: 40, num_layers: 40
Model variant detected: 14B
model_type FLOW
Loading LoRA: Wan21_CausVid_14B_T2V_lora_rank32 with strength: 0.6200000000000003
Loading model and applying LoRA weights:: 100%|█████████████████████████████████████████████████████████████| 737/737 [01:41<00:00,  7.29it/s]
Moving video model to cpu
Killed
'''

**Comment by unjadded** [comment]
I had the LORA low_mem_load set to `true`  but then flipped to `false` and still failed at the same step which is the ENCODE step shown in the image above

**Comment by unjadded** [comment]
Ok yay I got it working.

Blocks 35
VACE block 13
load the lora on NVRAM
quantize the text encoder

RAM is 96% NVRAM is 97%

Still surprises me 64GB of system memory isn't enough for this workflow but i suppose 720p is a beast

**Comment by Song367** [comment]
> Ok yay I got it working.
> 
> Blocks 35 VACE block 13 load the lora on NVRAM quantize the text encoder
> 
> RAM is 96% NVRAM is 97%
> 
> Still surprises me 64GB of system memory isn't enough for this workflow but i suppose 720p is a beast

low_mem_load=true    Adding commands at startup will fix the cpu blowing up?

**Comment by unjadded** [comment]
Hmm now I'm at 128GB system memory but it's still blowing up VRAM (24GB) on the WanVideoSampler step

- Ran comfy with no extra settings
- offload device enabled for all nodes
- Lora also low_mem_load=true
- text and img embeddings offloaded
- block swap 35 and 13 for for WAN VACE

<img width="1020" height="426" alt="Image" src="https://github.com/user-attachments/assets/29962c73-3776-4546-a611-017e49724d83" />

**Comment by unjadded** [comment]
Blcok swap 40 and vace swap 15, it finally ran the sampler but 99% VRAM used..still seems a little high... thoughts?

**Comment by kijai** [comment]
> Blcok swap 40 and vace swap 15, it finally ran the sampler but 99% VRAM used..still seems a little high... thoughts?

What resolution and frame count? With full block swap in fp8 even 720p should fit under 15GB so that doesn't sound right.

**Comment by kijai** [comment]
> > Blcok swap 40 and vace swap 15, it finally ran the sampler but 99% VRAM used..still seems a little high... thoughts?
> 
> What resolution and frame count? With full block swap in fp8 even 720p should fit under 15GB so that doesn't sound right.

Torch compile would reduce VRAM use a lot, if you can't use that you can also try changing the rope_function in the sampler to the new chunked option.

**Comment by unjadded** [comment]
<img width="308" height="308" alt="Image" src="https://github.com/user-attachments/assets/aceb2869-4da1-49c7-b306-16d4027d4409" />

20 force rate
185 frames

I don't have Torch compile node there, i'll try to add one. Any example workflows where you have that?

I only have default or comfy for rope_function, ill update your code to the latest version in comfy, i might be on an old version now?

**Comment by kijai** [comment]
> <img alt="Image" width="308" height="308" src="https://private-user-images.githubusercontent.com/2336892/466838613-aceb2869-4da1-49c7-b306-16d4027d4409.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTI2NDcxMDMsIm5iZiI6MTc1MjY0NjgwMywicGF0aCI6Ii8yMzM2ODkyLzQ2NjgzODYxMy1hY2ViMjg2OS00ZGExLTQ5YzctYjMwNi0xNmQ0MDI3ZDQ0MDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDcxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA3MTZUMDYyMDAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDE3ZjJlZTkwZDc1NWI2NmQyOTNjMjlkM2ZjOTBmNmVlMWNkMzI0ZDQ0NzRmNWViZTBhNTUwYmQ1YmYyMjAwYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.nAyhORT-QWtrvA6znu1iYbOZPVKahnZLOOvNookfeH0">
> 20 force rate 185 frames
> 
> I don't have Torch compile node there, i'll try to add one. Any example workflows where you have that?
> 
> I only have default or comfy for rope_function, ill update your code to the latest version in comfy, i might be on an old version now?

It's a lot of frames, that doesn't actually show the real resolution as that's coming from somewhere else though, if it's on the high side too this is expected to use a lot of VRAM.

Torch.compile is just connecte to the model loader compile_args, default settings are fine, if you can use sageattn you might be able to use it, but since it needs Triton as well it can be complicated to get working. The chunked setting is very new indeed, experimental but in cases where compile isn't used it gives similar memory savings but without the speed boost.

**Comment by unjadded** [comment]
Will give it a shot tomorrow. I have Triton working already with sageattn
enabled.

Reso was 896x512 for final output video.

Thanks!

J

**Comment by unjadded** [comment]
Torch.Compile worked great, thanks Kijai. NVRAM dropped to 68%, i was able to loosen up the block swap a bit too and enabled comfy_chunked.

System ram held well at 62%.

24 FPS worked great!
